export default () => ([
  {
    name: 'AppiumLibrary',
    href: 'https://github.com/serhatbolsu/robotframework-appiumlibrary',
    description: 'Android and iOS testing. Uses Appium internally.',
    tags: ['mobile']
  },
  {
    name: 'ArchiveLibrary',
    href: 'https://github.com/MarketSquare/robotframework-archivelibrary',
    description: 'Handling zip- and tar-archives.',
    tags: ['zip']
  },
  {
    name: 'AutoItLibrary',
    href: 'https://github.com/nokia/robotframework-autoitlibrary',
    description: 'Windows GUI testing library that uses AutoIt freeware tool as a driver.',
    tags: ['windows', 'ui']
  },
  {
    name: 'AutoRecorder',
    href: 'https://github.com/sebastianciupinski/robotframework-autorecorder#readme',
    description: 'Allows automatically recording video for test/suites execution.',
    tags: ['visual']
  },
  {
    name: 'Browser Library',
    href: 'https://github.com/MarketSquare/robotframework-browser',
    description: 'A modern web testing library powered by <a href="https://playwright.dev" target="_blank"> Playwright</a>. Aiming for speed, reliability and visibility.',
    tags: ['web']
  },
  {
    name: 'Clang Library',
    href: 'https://github.com/maxrossello/robotframework-clang',
    description: 'Just-in-Time unit testing of C++ code powered by Clang-REPL. No compilation needed.',
    tags: ['unit', 'c++']
  },
  {
    name: 'CncLibrary',
    href: 'https://github.com/eficode/robotframework-cnclibrary',
    description: 'Driving a CNC milling machine.',
    tags: ['rpa']
  },
  {
    name: 'ConfluentKafkaLibrary',
    href: 'https://github.com/robooo/robotframework-ConfluentKafkaLibrary',
    description: 'Python confluent kafka.'
  },
  {
    name: 'CURFLibrary',
    href: 'https://github.com/Openwide-Ingenierie/robotframework-can-uds-library',
    description: 'Testing CAN bus with support for ISO-TP and UDS.'
  },
  {
    name: 'Database Library (Java)',
    href: 'https://github.com/MarketSquare/robotframework-dblibrary',
    description: 'Java-based library for database testing. Usable with Jython. Available also at <a href="https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22robotframework-dblibrary%22" target="_blank">Maven central</a>.',
    tags: ['java']
  },
  {
    name: 'Database Library (Python)',
    href: 'https://github.com/MarketSquare/Robotframework-Database-Library',
    description: 'Python based library for database testing. Works with any Python interpreter, including Jython.',
    tags: ['db']
  },
  {
    name: 'DataDriver Library',
    href: 'https://github.com/Snooz82/robotframework-datadriver',
    description: 'Data-Driven Testing with external 📤 data tables (csv, xls, xlsx, etc.). 🧬 Pairwise Combinatorial Testing support.',
    tags: ['db']
  },
  {
    name: 'DebugLibrary',
    href: 'https://github.com/imbus/robotframework-debuglibrary',
    description: 'A debug library for RobotFramework, which can be used as an interactive shell(REPL) also.'
  },
  {
    name: 'Dependency Library',
    href: 'https://github.com/mentalisttraceur/robotframework-dependencylibrary',
    description: 'Declare dependencies between tests. Ideally tests are independent, but when tests depend on earlier tests, DependencyLibrary makes it easy to explicitly declare these dependencies and have tests that depend on each other do the right thing.'
  },
  {
    name: 'Diff Library',
    href: 'https://github.com/MarketSquare/robotframework-difflibrary',
    description: 'Diff two files together.'
  },
  {
    name: 'Django Library',
    href: 'https://github.com/kitconcept/robotframework-djangolibrary',
    description: 'Library for <a href="https://www.djangoproject.com/" target="_blank">Django</a>, a Python web framework.',
    tags: ['django']
  },
  {
    name: 'DocTest Library',
    href: 'https://github.com/manykarim/robotframework-doctestlibrary',
    description: 'Library for Document Testing, offers visual/content comparisons and masks for images, PDFs and more.',
    tags: ['pdf', 'visual']
  },
  {
    name: 'DoesIsLibrary',
    href: 'https://github.com/sebastianciupinski/robotframework-doesislibrary#readme',
    description: 'Autogenerated keywords like Is Something, Does Someting created form assertion keywords like Should Be, Should Not Be, etc'
  },
  {
    name: 'DoIP Library',
    href: 'https://github.com/test-fullautomation/robotframework-doip',
    description: 'DoIP (Diagnostic over Internet Protocol) keyword library based on <a href="https://pypi.org/project/doipclient/" target="_blank">doipclient</a>. This library is part of the <a href="https://robotframework-aio.org" target="_blank">RobotFramework AIO</a> (All In One) OSS project.',
    tags: ['embedded', 'automotive']
  },
  {
    name: 'Eclipse Library',
    href: 'https://github.com/lcarbonn/robotframework-eclipselibrary/',
    description: 'Testing Eclipse RCP applications using SWT widgets.'
  },
  {
    name: 'FTP library',
    href: 'https://github.com/kowalpy/Robot-Framework-FTP-Library',
    description: 'Testing and using FTP server with Robot Framework.',
    tags: ['ftp']
  },
  {
    name: 'HTTP RequestsLibrary (Python)',
    href: 'https://github.com/MarketSquare/robotframework-requests#readme',
    description: 'HTTP level testing using Python Requests internally.',
    tags: ['http']
  },
  {
    name: 'HttpRequestLibrary (Java)',
    href: 'https://github.com/MarketSquare/robotframework-httprequestlibrary',
    description: 'HTTP level testing using Apache HTTP client. Available also at <a href="https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22robotframework-httprequestlibrary%22" target="_blank">Maven central</a>.',
    tags: ['http', 'java']
  },
  {
    name: 'ImageHorizonLibrary',
    href: 'https://github.com/eficode/robotframework-imagehorizonlibrary#readme',
    description: 'Cross-platform, pure Python library for GUI automation based on image recognition.',
    tags: ['ui', 'visual']
  },
  {
    name: 'JavaFXLibrary',
    href: 'https://github.com/eficode/JavaFXLibrary#readme',
    description: 'Testing JavaFX applications, based on <a href="https://github.com/TestFX/TestFX" target="_blank">TestFX</a>. Has also remote interface support.',
    tags: ['java']
  },
  {
    name: 'KiCadLibrary',
    href: 'https://github.com/madworx/robotframework-kicadlibrary#readme',
    description: 'Interacting with KiCad EDA designs.'
  },
  {
    name: 'ListenerLibrary',
    href: 'https://github.com/sebastianciupinski/robotframework-listenerlibrary#readme',
    description: 'Register keywords to run before/after other keywords and suites.'
  },
  {
    name: 'Mainframe3270 Library',
    href: 'https://github.com/MarketSquare/Robot-Framework-Mainframe-3270-Library/blob/master/README.md',
    description: 'Allows the creation of automated test scripts to test IBM Mainframe 3270.',
    tags: ['ibm']
  },
  {
    name: 'MQTT library',
    href: 'https://github.com/randomsync/robotframework-mqttlibrary#readme',
    description: 'Testing MQTT brokers and applications.',
    tags: ['iot']
  },
  {
    name: 'OracleDBLibrary',
    href: 'https://github.com/adeliogullari/robotframework-oracledb-library',
    description: 'A database testing library for Robot Framework that utilizes the python-oracledb tool internally.',
    tags: ['db', 'oracle', 'oracledb']
  },
  {
    name: 'PuppeteerLibrary',
    href: 'https://github.com/qahive/robotframework-puppeteer',
    description: 'Web testing using Puppeteer tool internally.',
    tags: ['web', 'ui']
  },
  {
    name: 'Qweb',
    href: 'https://github.com/qentinelqi/qweb',
    description: 'A modern web testing library focusing on making web testing and automation Easy 🎉 and maintainable 🧹 with its high level keyword design.',
    tags: ['web', 'ui']
  },
  {
    name: 'Rammbock',
    href: 'https://github.com/MarketSquare/Rammbock#readme',
    description: 'Generic network protocol test library that offers easy way to specify network packets and inspect the results of sent and received packets.',
    tags: ['http']
  },
  {
    name: 'RemoteSwingLibrary',
    href: 'https://github.com/MarketSquare/remoteswinglibrary',
    description: 'Testing and connecting to a java process and using SwingLibrary, especially Java Web Start applications.',
    tags: ['java']
  },
  {
    name: 'RESTinstance',
    href: 'https://github.com/asyrjasalo/RESTinstance/',
    description: 'Test library for HTTP JSON APIs.',
    tags: ['http']
  },
  {
    name: 'Robotframework-faker',
    href: 'https://github.com/MarketSquare/robotframework-faker',
    description: 'Library for <a href="https://github.com/joke2k/faker" target="_blank">Faker</a>, a fake test data generator.'
  },
  {
    name: 'Robotframework-FlaUI',
    href: 'https://github.com/GDATASoftwareAG/robotframework-flaui',
    description: 'Robotframework-FlaUI is a keyword based user interface automation testing library for Windows applications like Win32, WinForms, WPF or Store Apps. It\'s based on the FlaUI user interface automation library.',
    tags: ['windows', 'ui']
  },
  {
    name: 'Robotframework-MailClientLibrary',
    href: 'https://github.com/noubar/RobotFramework-MailClientLibrary',
    description: 'The Robotframework-MailClientLibrary is a keyword-based mail client library that supports testing of mail protocols, including IMAP, POP3, and SMTP with or without SSL connection.',
    tags: ['mail', 'imap', 'smtp', 'pop3', 'ssl']
  },
  {
    name: 'Robotframework-XmlValidator',
    href: 'https://github.com/MichaelHallik/robotframework-xmlvalidator',
    description: 'A Robot Framework test library for validating XML files against XSD schemas, and more.',
    tags: ['xml', 'xsd', 'xmlschema']
  },
  {
    name: 'SapGuiLibrary',
    href: 'https://github.com/frankvanderkuur/robotframework-sapguilibrary/',
    description: 'Testing the SAPGUI client using the internal SAP Scripting Engine',
    tags: ['ui', 'sap']
  },
  {
    name: 'RoboSAPiens',
    href: 'https://github.com/imbus/robotframework-robosapiens',
    description: '<a href="https://github.com/imbus/robotframework-robosapiens" target="_blank">RoboSAPiens</a> is a library for automating the Windows SAP GUI. Its key innovation (compared to <a href="https://github.com/frankvanderkuur/robotframework-sapguilibrary/" target="_blank">SapGuiLibrary</a>) is that UI elements can be selected using the texts in the GUI. No need to use a third-party tool to find some XPath-like selectors. Moreover, RoboSAPiens is under active development.',
    tags: ['ui', 'sap']
  },
  {
    name: 'ScreenCapLibrary',
    href: 'https://github.com/rticau/ScreenCapLibrary',
    description: 'Taking screenshots and video recording. Similar functionality as Screenshot standard library, with some additional features.',
    tags: ['ui']
  },
  {
    name: 'SeleniumScreenshots',
    href: 'https://github.com/MarketSquare/robotframework-seleniumscreenshots',
    description: 'Annotating and cropping screenshots taken with SeleniumLibrary.',
    tags: ['ui', 'selenium']
  },
  {
    name: 'SeleniumLibrary',
    href: 'https://github.com/robotframework/SeleniumLibrary/',
    description: 'Web testing library that uses popular Selenium tool internally.',
    tags: ['web', 'selenium']
  },
  {
    name: 'SeleniumLibrary for Java',
    href: 'https://github.com/MarketSquare/robotframework-seleniumlibrary-java#readme',
    description: 'Java port of the SeleniumLibrary.',
    tags: ['java', 'selenium']
  },
  {
    name: 'SikuliLibrary',
    href: 'https://github.com/MarketSquare/robotframework-SikuliLibrary#readme',
    description: 'Provides keywords to test UI through <a href="https://sikulix.com/" target="_blank">Sikulix</a>. This library supports Python 2.x and 3.x.',
    tags: ['ui']
  },
  {
    name: 'SoapLibrary',
    href: 'https://github.com/MarketSquare/Robot-Framework-SOAP-Library',
    description: 'Designed for those who want to work with webservice automation as if they were using SoapUI, make a request through an XML file, and receive the response in another XML file.',
    tags: ['http']
  },
  {
    name: 'SSHLibrary',
    href: 'https://github.com/MarketSquare/SSHLibrary',
    description: 'Enables executing commands on remote machines over an SSH connection. Also supports transfering files using SFTP.',
    tags: ['ftp', 'ssh']
  },
  {
    name: 'SwingLibrary',
    href: 'https://github.com/MarketSquare/SwingLibrary/wiki',
    description: 'Testing Java applications with Swing GUI.',
    tags: ['java', 'ui']
  },
  {
    name: 'TestFX Library',
    href: 'https://github.com/Altran-PT-GDC/Robot-Framework-Test-FX-Library',
    description: 'Enables testing Java FX applications using the <a href="https://github.com/TestFX/TestFX" target="_blank">TestFX framework</a>. Has also remote interface support. <a href="https://github.com/weiqigao/Robot-Framework-Test-FX-Library" target="_blank">Maintained Fork...</a>',
    tags: ['java']
  },
  {
    name: 'TFTPLibrary',
    href: 'https://github.com/kowalpy/Robot-Framework-TFTP-Library',
    description: 'Interact over <a href="https://en.wikipedia.org/wiki/Trivial_File_Transfer_Protocol" target="_blank">Trivial File Transfer Portocol</a>.',
    tags: ['ftp']
  },
  {
    name: 'WADLibrary',
    href: 'https://github.com/rogerjagaredev/WADLibrary',
    description: 'Application testing library that utilizes Win App Driver.',
    tags: ['windows']
  },
  {
    name: 'Zoomba Library',
    href: 'https://github.com/Accruent/robotframework-zoomba',
    description: 'Extends features in many popular tools for GUI, Rest API, Soap API, Mobile, and Windows (WinAppDriver) automation. An ideal all-in-one toolkit for new or existing Robot Framework projects.',
    tags: ['ui', 'http']
  },
  {
    name: 'Python Library Core',
    href: 'https://github.com/robotframework/PythonLibCore',
    description: 'Tools to ease creating larger test libraries for Robot Framework using Python.',
    tags: ['tools']
  },
  {
    name: 'JavalibCore',
    href: 'https://github.com/robotframework/JavalibCore/wiki',
    description: 'Base for implementing larger Java based test libraries for Robot Framework.',
    tags: ['java']
  },
  {
    name: 'RemoteApplications',
    href: 'https://github.com/robotframework/RemoteApplications',
    description: 'Special test library for launching Java applications on a separate JVM and taking other libraries into use on them.',
    tags: ['java']
  },
  {
    name: 'Plone.app .robotframework',
    href: 'https://github.com/plone/plone.app.robotframework/',
    description: 'Provides resources and tools for writing functional Selenium tests for Plone CMS and its add-ons.',
    tags: ['selenium']
  },
  {
    name: 'UDS Library',
    href: 'https://github.com/test-fullautomation/robotframework-uds',
    description: 'UDS (Unified Diagnostic Services) keyword library based on <a href="https://pypi.org/project/udsoncan/" target="_blank">udsoncan</a>, <a href="https://pypi.org/project/doipclient/" target="_blank">doipclient</a> and <a href="https://pypi.org/project/odxtools/" target="_blank">odxtools</a>. This library is part of the <a href="https://robotframework-aio.org" target="_blank">RobotFramework AIO</a> (All In One) OSS project.',
    tags: ['embedded', 'automotive']
  },
  {
    name: 'WatchUI',
    href: 'https://github.com/Tesena-smart-testing/WatchUI',
    description: 'Visual testing library for visual difference testing as well as image content testing (including PDF documents). Runs on Selenium to generate screenshots, uses PyMuPDF to process PDFs and Tesseract OCR to recognize text.',
    tags: ['ui']
  },
  {
    name: 'KubeLibrary',
    href: 'https://github.com/devopsspiral/KubeLibrary',
    description: 'A library to interact with the Kubernetes API',
    tags: ['cloud', 'infrastructure']
  },
  {
    name: 'Terraform Library',
    href: 'https://github.com/Nilsty/robotframework-terraformlibrary',
    description: 'A library providing Infrastructure as Code capabilities via Terraform and OpenTofu',
    tags: ['cloud', 'infrastructure']
  }
])
